import Image from 'next/image'
import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Leo Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link  rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="p-10 text-red-500">test</h1>
      </div>
  )
}
