import React, { useEffect, useState, Suspense } from 'react';
import Head from 'next/head'
import Page from '../components/Page';
import { useTranslation } from "react-i18next";
import { pages } from "../utils";
import ViewTimelineIcon from '@mui/icons-material/ViewTimeline';

const Home = () => {
  const { t, i18n } = useTranslation();

  async function changeLocale () {
    if (i18n.language === 'en') {
      i18n.changeLanguage('fr');
    }
    else {
      i18n.changeLanguage('en');
    }
  }
  
  
  const [pageCounter, setPageCounter] = useState({ value1: 0, value2: 0, min: 0, max: pages.length - 1})
  return (
    <div className="bg-[rgb(36,36,36)] z-10 text-white flex flex-col justify-center h-screen">
      <Head>
        <title>Leo Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link  rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-1 justify-center items-center h-screen">
        <div className="h-5/6 mr-5 flex">
          <div className="flex items-center w-9 pt-5 pb-5 flex-col text-black justify-between bg-[#FF6665]">
            <button onClick={() => changeLocale()} type="button" className="rotate-m90 underline" >EN/FR</button>
            <p className="truncate rotate-m90">Leo Goubard</p>
            <p className="rotate-m90 truncate m-14">{t('cover.job')}</p>
          </div>
        </div>
        {pages[pageCounter.value1] && (
          <Page pageMax={pageCounter.max} key={pages[pageCounter.value1].index} setPageCounter={setPageCounter} pageItem={pages[pageCounter.value1]}/>
        )}
        {pages[pageCounter.value2] && pageCounter.value1 !== 0 &&  (
          <>
            <div className="h-5/6 w-3 bg-gradient-to-r from-[#F9F9F9]  via-[rgb(166,165,165)] to-[#F9F9F9]" />
                <Page pageMax={pageCounter.max} key={pages[pageCounter.value2].index} setPageCounter={setPageCounter} pageItem={pages[pageCounter.value2]}/>
          </>
        )}
        {pageCounter.value1 !== 1 && pageCounter.value1 !== 0 && (<div onClick={() => setPageCounter(
              (prevState: any) => (
                {
                  ...prevState,
                  value1: 1,
                  value2: 2
                }
              )
            )} className="absolute cursor-pointer top-8 left-[20%] h-10 w-20 flex flex-col text-center justify-center"><ViewTimelineIcon /></div>)}
      </div>
    </div>
  )
}

export default Home;